### ISSUE TITLE
Samples code not working at all

### ISSUE THREAD

**Issue by JadaVonRuth** [dotnet/AspNetCore.Docs.cs-cz#21]
[Sem napište váš názor.]
If you try your code for google auth all you will get is error message 

"No authenticationScheme was specified, and there was no DefaultChallengeScheme found. The default schemes can be set using either AddAuthentication(string defaultScheme) or AddAuthentication(Action<AuthenticationOptions> configureOptions)" 

which is kinda funny becase AddAuthentication was called in your code.

---
#### Podrobnosti dokumentu

⚠ *Neupravujte tuto část. Vyžaduje se k propojení problémů docs.microsoft.com ➟ GitHub.*

* ID: 6d19b295-f935-3755-4ca4-9d0717b21e75
* Version Independent ID: 747a179e-90b7-de07-e270-82414963048a
* Content: [Nastavení externího přihlášení Google v ASP.NET Core](https://docs.microsoft.com/cs-cz/aspnet/core/security/authentication/social/google-logins?view=aspnetcore-5.0)
* Content Source: [aspnetcore/security/authentication/social/google-logins.md](https://github.com/dotnet/AspNetCore.Docs.cs-cz/blob/live/aspnetcore/security/authentication/social/google-logins.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
The tutorial works. I'm not sure what step you missed. You might try asking on StackOverflow,.
